auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki  # Fix compactor error

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb  # Upgrade from boltdb-shipper to tsdb
      object_store: filesystem
      schema: v13  # Upgrade from v11 to v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false  # Temporarily disable structured metadata

compactor:
  working_directory: /loki/compactor  # Fix missing working_directory
