auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

schema_config:
  configs:
    - from: 2025-02-26
      store: boltdb-shipper
      object_store: azure
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    shared_store: azure
  azure:
    container_name: loki-data
    account_name: "{{DOCKER_REGISTRY_SERVER_USERNAME}}"
    account_key: "{{DOCKER_REGISTRY_SERVER_PASSWORD}}"

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
