# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rest-api-test

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://loadtestlog.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5c59346df70f4aa9ba9d67e57efe0d16 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_715b3269cbb54e06beaa96a7b47baf92 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: loadtestlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5c59346df70f4aa9ba9d67e57efe0d16 }}/restapitest:${{ github.sha }}
        file: ./Rest-Api-Test/Rest-Api-Test/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rest-api-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c8454dcd68a542798328df48600df09b }}
        images: 'loadtestlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5c59346df70f4aa9ba9d67e57efe0d16 }}/restapitest:${{ github.sha }}'
