# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - loadtestlog-influxdb-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://loadtestlog.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4c08de88d9de4a93a61e34993126d042 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6c1d873248d84e2890c12cb4f22603b5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: loadtestlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4c08de88d9de4a93a61e34993126d042 }}/influxdb:${{ github.sha }}
        file: ./influxdb-dockerfile/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'loadtestlog-influxdb-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_18a65031734e4c1fb4fc00ff704c5a13 }}
        images: 'loadtestlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4c08de88d9de4a93a61e34993126d042 }}/influxdb:${{ github.sha }}'
