# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - loadtestlog-grafana-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://loadtestlog.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f5663a858ff44a8e9014602b1b0033d3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e1b15f8dc2a4f478d6d14fd5c89efe6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: loadtestlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f5663a858ff44a8e9014602b1b0033d3 }}/loadtestlog/grafana/grafana:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'loadtestlog-grafana-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4012651047dd426e91231f163c9d7330 }}
        images: 'loadtestlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f5663a858ff44a8e9014602b1b0033d3 }}/loadtestlog/grafana/grafana:${{ github.sha }}'